kind: pipeline
type: docker
name: Creeate ascii based list

platform:
  os: linux
  arch: amd64

steps:
  - name: Create ascii based list
    image: debian:bullseye
    commands:
    - ./convert_list.sh
  - name: Push changes
    image: appleboy/drone-git-push
    settings:
      branch: main
      remote:
         from_secret: GH_REPO
      force: false
      commit: true
      commit_message: "Update ascii list [CI SKIP]"
      author_name: drone-bot
      author_email: drone-bot@hestiacp.com
trigger:
       event: [ push ] 