kind: pipeline
type: docker
name: Creeate ascii based list

platform:
  os: linux
  arch: amd64

steps:
  - name: Create ascii based list
    image: debian:bullseye
    commands:
    - ./convert_list.sh
  - name: push
    image: appleboy/drone-git-push
    settings:
    branch:  main
    remote: git@github.com:jaapmarcus/publicsuffix-ascii-list.git
    commit: true
    commit_message: test
    ssh_key:
      from_secret: ssh_key
trigger:
       event: [ push ] 