kind: pipeline
type: docker
name: Creeate ascii based list

platform:
  os: linux
  arch: amd64

steps:
  - name: Create ascii based list
    image: debian:bullseye
    commands:
    - ./convert_list.sh
  - name: push commit
    image: appleboy/drone-git-push
    settings:
      remote_name: origin
      branch: main
      force: false
      commit: true
trigger:
       event: [ push ] 