kind: pipeline
type: docker
name: Creeate ascii based list

platform:
  os: linux
  arch: amd64

steps:
  - name: Create ascii based list
    image: debian:bullseye
    commands:
    - ./convert_list.sh
  - name: Commit changes
    image: appleboy/drone-git-push
    settings:
      branch: main
      remote: git@github.com:jaapmarcus/publicsuffix-ascii-list.git
      key: 
        from_secret: ssh_key
      force: false
      commit: true
trigger:
       event: [ push ] 