kind: pipeline
type: docker
name: Creeate ascii based list

platform:
  os: linux
  arch: amd64

steps:
  - name: Create ascii based list
    image: debian:bullseye
    commands:
    - ./convert_list.sh
    
trigger:
       event: [ push ] 